version: "3"

services:
  kronic:
    image: ghcr.io/mshade/kronic
    build:
      context: .
      target: dev
    environment:
      KRONIC_ALLOW_NAMESPACES: "test"
    volumes:
      - .:/app
      - $HOME/.kube/kronic.yaml:/root/.kube/config
    ports:
      - 5000:5000
    networks:
      - k3d-kronic

networks:
  k3d-kronic:
    external: true
