{{- if and (and .Values.ingress.enabled .Values.ingress.auth.enabled) (not .Values.ingress.auth.secretName) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kronic.fullname" . }}
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
data:
  auth: {{ htpasswd .Values.ingress.auth.username .Values.ingress.auth.password | b64enc | quote }}
{{- end }}
