{{- if and .Values.auth.enabled (not .Values.auth.existingSecretName) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kronic.fullname" . }}
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
data:
  password: {{ include "kronic.adminPassword" . | b64enc | quote }}
{{- end }}
