{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
  name: {{ include "kronic.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
      - pods/log
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
      - cronjobs/status
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kronic.labels" . | nindent 4 }}
  name: {{ include "kronic.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kronic.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kronic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
