apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello1
  namespace: test
spec:
  jobTemplate:
    metadata:
      name: hello1
    spec:
      template:
        spec:
          containers:
          - command:
            - echo
            - hello
            image: busybox
            name: hello1
            resources: {}
          restartPolicy: OnFailure
  schedule: 0/5 * * * *
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello2
  namespace: test
spec:
  jobTemplate:
    metadata:
      name: hello2
    spec:
      completions: 3
      template:
        spec:
          containers:
          - command:
            - echo
            - hello
            image: busybox
            name: hello2
            resources: {}
          restartPolicy: OnFailure
  schedule: '* * * * *'
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-reports
  namespace: prod
spec:
  jobTemplate:
    metadata:
      name: user-reports
    spec:
      template:
        spec:
          containers:
          - command: ["/bin/ash", "-c"]
            args:
              - wget https://jsonplaceholder.typicode.com/users/ -O - -q --no-check-certificate
            image: busybox
            name: user-reports
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/10 * * * *'
  suspend: true
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example
  namespace: prod
spec:
  jobTemplate:
    metadata:
      name: example
    spec:
      completions: 3
      template:
        spec:
          containers:
          - command:
            - echo
            - example
            image: busybox
            name: example
            resources: {}
          restartPolicy: OnFailure
  schedule: 0/5 * * * *
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-longlines
  namespace: test
spec:
  jobTemplate:
    metadata:
      name: example
    spec:
      completions: 1
      template:
        spec:
          containers:
          - command:
            - ash 
            - -c
            - |
              while true; do seq -s '' 1 999; sleep 1; done
            image: busybox
            name: example
            resources: {}
          restartPolicy: OnFailure
  schedule: 0/5 * * * *
