# Default values for kronic - the simple Kubernetes CronJob Admin UI

# -- Number of replicas in deployment - min 2 for HA
replicaCount: 1

image:
  repository: ghcr.io/mshade/kronic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""


auth:
  # -- Enable backend basic auth
  enabled: true
  # -- Specify a password via chart value. Otherwise, randomly generated on first deploy.
  adminPassword: ""
  # -- Set the username for auth
  adminUsername: "kronic"
  # -- Provide the name of a pre-existing secret containing a data.password: xxx
  existingSecretName: ""

env:
  # -- Comma separated list of namespaces to allow access to, eg: "staging,qa,example"
  KRONIC_ALLOW_NAMESPACES: ""
  # -- Limit Kronic to its own namespace. Set to "true" to enable.
  KRONIC_NAMESPACE_ONLY: ""

# Specify whether to create ClusterRole and ClusterRoleBinding
# for kronic. If disabled, you will need to handle permissions
# manually.
rbac:
  # -- Create ClusterRole, ClusterRoleBindings, Role, RoleBindings for cronjob/job/pod permissions.
  enabled: true

serviceAccount:
  # Specifies whether the kronic service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use for kronic. Useful to handle RBAC on your own.
  # name: "kronic"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  # -- Expose Kronic via Ingress
  enabled: false
  # -- The ingressClassName to use for Kronic. Avoid exposing publicly!
  className: ""
  # -- Additional annotations for ingress. Use to configure more advanced auth or controllers other than ingress-nginx
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- the ingress hostname(s) for Kronic
  hosts:
    - host: kronic-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 256Mi

nodeSelector: {}

tolerations: []

# -- Provide scheduling affinity selectors
affinity: {}
